### ISSUE TITLE
Send PR to PostCSS README

### ISSUE THREAD

**Issue by ai** [iamstarkov/postcss-color-mix#1]
Awesome plugin.

Please, send a PR with this plugin in Color section in PostCSS README.md

**Comment by iamstarkov** [comment]
sure, but I need to fix [last test](https://github.com/iamstarkov/postcss-color-mix/blob/master/test.js#L29-L34) and i’m already spent huge amount of time only on this test case. So I probably will take a break, then fix it and of course will send pr after

**Comment by iamstarkov** [comment]
btw, its done
